version: '3'
services:
  yelp-client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    volumes:
      - "./client/src:/usr/app/src/src"

  yelp-server:
    build:
      context: ./server
    ports:
      - "3000:3000"
